spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/backend?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1116

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: aW5waXQtYmFja2VuZC0xMWJpdC1zZWNyZXQta2V5LWZvci1qd3QtYXV0aGVudGljYXRpb24tMjAyNg==
  expiration: 86400000

server:
  port: 8080